# Generated by Django 4.1.7 on 2023-03-09 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('zipcode', models.BigIntegerField()),
                ('subscribers', models.ManyToManyField(related_name='playdate_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
