# Generated by Django 4.1.7 on 2023-03-12 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playdate', '0002_playdate_date_playdate_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playdate',
            old_name='subscribers',
            new_name='subscribers_id',
        ),
    ]
