# Generated by Django 4.1.7 on 2023-03-09 20:28

from django.db import migrations, models
 

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=60)),
                ('weight', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
