# Generated by Django 4.1.7 on 2023-03-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_dogs_image_url_dogs_spayedorneutered'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogs',
            name='name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
