# Generated by Django 4.1.7 on 2023-03-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_rating', models.BigIntegerField()),
                ('owner_rating', models.BigIntegerField()),
                ('play_date_rating', models.BigIntegerField()),
                ('review', models.CharField(max_length=600)),
            ],
        ),
    ]
